src/objects/Indicator__mdt.object
<CustomObject>
    <description>Individual indicators in the Weather Vane indicator strip.</description>
    <fields>
        <fullName>Contains_Value__c</fullName>
        <inlineHelpText>If indicator type is &quot;Contains&quot;, indicator will be enabled if the field specified in Field API Name contains this string. If indicator type is &quot;greater than&quot;/&quot;less than&quot;, indicator will be enabled if the field specified is greater than/less than this val.</inlineHelpText>
        <label>Compare Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Disabled_Color__c</fullName>
        <defaultValue>&quot;grey&quot;</defaultValue>
        <inlineHelpText>If the indicator criteria are not met, it will be displayed in this color. Usually a greyed out version is appropriate.</inlineHelpText>
        <label>Disabled Color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_Value__c</fullName>
        <inlineHelpText>The short text string to display on the indicator.</inlineHelpText>
        <label>Display Value</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enabled_Color__c</fullName>
        <inlineHelpText>If the indicator conditions ARE met, the indicator is displayed in this color. Supports HTML color names and hexcodes.</inlineHelpText>
        <label>Enabled Color</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Entity__c</fullName>
        <label>Entity</label>
        <picklist>
            <picklistValues>
                <fullName>Contact</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Field_API_Name__c</fullName>
        <inlineHelpText>API Name of the field which drives this indicator.</inlineHelpText>
        <label>Field API Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Grid_Order__c</fullName>
        <inlineHelpText>Order of this indicator in the indicator grid.</inlineHelpText>
        <label>Grid Sort Order</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Hover_Text__c</fullName>
        <inlineHelpText>Hover text that will appear on the Indicator badge.</inlineHelpText>
        <label>Hover Text</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>Select the type of indicator grid entry this should be. Contains uses the Contains Value field to check if the string is present. Boolean checks to see if the field is true or false. Blank adds a blank space in the grid, useful for separating indicators.</inlineHelpText>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Contains</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Boolean</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Is Not Null</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Blank Space</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Indicator</label>
    <pluralLabel>Indicators</pluralLabel>
</CustomObject>

src/classes/Indicators_Service.cls
public class Indicators_Service {
    public static List<Indicator> getIndicatorsForObject(SObject sob) {
        List<Indicator> result = new List<Indicator>();
        for(Indicator__mdt config : [SELECT DeveloperName, Grid_Order__c,
                                     Field_API_Name__c, Enabled_Color__c,
                                     Contains_Value__c, Display_Value__c,
                                     Disabled_Color__c, Type__c, Hover_Text__c
                                     FROM Indicator__mdt
                                     WHERE Entity__c = :sob.getSObjectType().getDescribe().getName()
                                     ORDER BY Grid_Order__c]) {
                                         result.add(evaluateIndicator(config,sob));
                                     }
        return result;
    }

    public static List<String> getFieldNamesForObject(SObjectType t) {
        Set<String> result = new Set<String>();
        for(Indicator__mdt config : [SELECT DeveloperName,  Field_API_Name__c FROM Indicator__mdt WHERE Field_API_Name__c != null AND Entity__c = :t.getDescribe().getName() ]) {
            result.add(config.Field_API_Name__c);
        }
        return new List<String>(result);
    }

    private static Indicator evaluateIndicator(Indicator__mdt config, SObject sob) {
        Object field = '';
        if(String.isNotBlank(config.Field_API_Name__c)) {
            field = sob.get(config.Field_API_Name__c);

        }
        Boolean enabled = false;
        Boolean display = true;
        if(config.Type__c == 'Contains') {
            if(String.isNotBlank((String)field) && String.isNotBlank(config.Contains_Value__c)) {
                enabled = ((String)field).contains(config.Contains_Value__c);
            }

        } else if(config.Type__c == 'Boolean') {
            enabled = (Boolean)field;
        } else if(config.Type__c == 'Is Not Null') {
            if(String.isNotBlank((String)field))
        		enabled = true;
        } else if(config.Type__c == 'Greater Than') {
            if(field != null && String.isNotBlank(config.Contains_Value__c)) {
                enabled = (Decimal.valueOf((String)field) > Decimal.valueOf(config.Contains_Value__c));
            }
        } else if(config.Type__c == 'Less Than') {
            if(field != null && String.isNotBlank(config.Contains_Value__c)) {
                enabled = (Decimal.valueOf((String)field) < Decimal.valueOf(config.Contains_Value__c));
            }
        } else if(config.Type__c == 'Blank') {
            enabled = false;
            display = false;
        }
        return new Indicator(config.Display_Value__c, enabled ? config.Enabled_Color__c : config.Disabled_Color__c, display, config.Hover_Text__c);
    }

    public class Indicator {
        public string Color {get;set;}
        public string Value {get;set;}
        public Boolean Display {get;set;}
        public string Hover {get;set;}

        public Indicator(String value, String color, Boolean display, String hover) {
            this.Value = value; this.Color = color; this.Display = display; this.Hover = hover;
        }
    }
}